development:
  adapter: mysql2
  encoding: utf8
  database: uspocupa_development
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: uspocupa_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: uspocupa_production
  pool: 5
  username: root
  password: 
  host: localhost
